<a href="https://colab.research.google.com/github/vidyakc111/Applications-of-Python-Programming-in-DA-ML-/blob/master/Day3_Session_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Program to create series

In [ ]:
import pandas as pd

In [ ]:

# Import Panda Library
# Program to Create series with scalar values
Data=[1,3,4,5,6,2,9]
# Numeric data
# Creating series with default index values
s=pd.Series(Data)
print(s)
# predefined index values
Index=['a','b','c','d','e','f','g']
# Create series with Data, and Index
a=pd.Series(Data,index=Index)
a

0    1
1    3
2    4
3    5
4    6
5    2
6    9
dtype: int64


a    1
b    3
c    4
d    5
e    6
f    2
g    9
dtype: int64

#Converting Pandas Series to Python list

In [ ]:

ds=pd.Series([2,4,6,8,10])
print("Pandas Series")
print(ds)
print("Convert Pandas Series to Python list")
ds.tolist()

Pandas Series
0     2
1     4
2     6
3     8
4    10
dtype: int64
Convert Pandas Series to Python list


[2, 4, 6, 8, 10]

#Program to Create Dictionary into Series

In [ ]:
dictionary={'a':1,'b':2,'c':3,'d':4,'e':5,'f':6}
# Creating series of Dictionary type
sd=pd.Series(dictionary)
sd

a    1
b    2
c    3
d    4
e    5
f    6
dtype: int64

#Program to Create ndarray series

In [ ]:
Data=[[2,3,4],[5,6,7]]
# Defining 2darray
print(Data)
# Creating series of 2darray
snd=pd.Series(Data)
snd

[[2, 3, 4], [5, 6, 7]]


0    [2, 3, 4]
1    [5, 6, 7]
dtype: object

#Program to Create DataFrame

In [ ]:
import pandas as pd
# Import Library
a=pd.DataFrame(Data)
a

0  1  2
0  2  3  4
1  5  6  7

#converting multiple dictionaries into pandas data frame

In [38]:
dict1={'a':35.2,'b':47,'c':77,'d':49}
# Define Dictionary 1
dict2={'a':53,'b':69,'c':79,'d':81,'e':91}
# Define Dictionary 2
dict3={'a':56,'b':98,'c':77,'d':81,'e':90}
# Define Dictionary 3
Data={'Maths':dict1,'Physics':dict2,'Chemistry':dict3}
# Define Data with dict1
df=pd.DataFrame(Data)
# Create DataFrame
df

Maths  Physics  Chemistry
a   35.2       53         56
b   47.0       69         98
c   77.0       79         77
d   49.0       81         81
e    NaN       91         90

#Program to create Dataframe of three series

In [40]:
import pandas as pd
s1=pd.Series([1,3,4,5,6,2,9])
# Define series 1
s2=pd.Series([1.1,3.5,4.7,5.8,2.9,9.3])
# Define series 2
s3=pd.Series(['a','b','c','d','e'])
# Define series 3
Data={'first':s1,'second':s2,'third':s3}
# Define Data
dfseries=pd.DataFrame(Data)
# Create DataFrame
dfseries

first  second third
0      1     1.1     a
1      3     3.5     b
2      4     4.7     c
3      5     5.8     d
4      6     2.9     e
5      2     9.3   NaN
6      9     NaN   NaN

#Program to create DataFrame from 2D array

In [42]:
import pandas as pd
# Import Library
d1=[[2,3,4],[5,6,7]]
# Define 2d array 1
d2=[[2,4,8],[1,3,9]]
# Define 2d array 2
Data={'first':d1,'second':d2}
# Define Data
df2d=pd.DataFrame(Data)
# Create DataFrame
df2d

first     second
0  [2, 3, 4]  [2, 4, 8]
1  [5, 6, 7]  [1, 3, 9]

#Converting Pandas Series to Python list

In [45]:
import pandas as pd
ds=pd.Series([2,4,6,8,10])
print("Pandas Series and type")
print(ds)
print(type(ds))
print("Convert Pandas Series to Python list")
print(ds.tolist())
print(type(ds.tolist()))

Pandas Series and type
0     2
1     4
2     6
3     8
4    10
dtype: int64
<class 'pandas.core.series.Series'>
Convert Pandas Series to Python list
[2, 4, 6, 8, 10]
<class 'list'>


#Write a Pandas program to add, subtract, multiple and divide two Pandas Series. Sample Series:
[2, 4, 6, 8, 10], [1, 3, 5, 7, 9]

In [48]:
import pandas as pd
ds1=pd.Series([2,4,6,8,10])
ds2=pd.Series([1,3,5,7,9])
ds=ds1+ds2
print("Add two Series:")
print(ds)
print("Subtract two Series:")
ds=ds1-ds2
print(ds)
print("Multiply two Series:")
ds=ds1*ds2
print(ds)
print("Divide Series1 by Series2:")
ds=ds1/ds2
print(ds)

Add two Series:
0     3
1     7
2    11
3    15
4    19
dtype: int64
Subtract two Series:
0    1
1    1
2    1
3    1
4    1
dtype: int64
Multiply two Series:
0     2
1    12
2    30
3    56
4    90
dtype: int64
Divide Series1 by Series2:
0    2.000000
1    1.333333
2    1.200000
3    1.142857
4    1.111111
dtype: float64


#Write a P dtype: float64 andas program to compare the elements of the two Pandas Series. Sample Series: [2,
4, 6, 8, 10], [1, 3, 5, 7, 9]

In [49]:
import pandas as pd
ds1=pd.Series([2,4,6,8,10])
ds2=pd.Series([1,3,5,7,10])
print("Series1:")
print(ds1)
print("Series2:")
print(ds2)
print("Compare the elements of the said Series:")
print("Equals:")
print(ds1==ds2)
print("Greater than:")
print(ds1>ds2)
print("Less than:")
print(ds1<ds2)

Series1:
0     2
1     4
2     6
3     8
4    10
dtype: int64
Series2:
0     1
1     3
2     5
3     7
4    10
dtype: int64
Compare the elements of the said Series:
Equals:
0    False
1    False
2    False
3    False
4     True
dtype: bool
Greater than:
0     True
1     True
2     True
3     True
4    False
dtype: bool
Less than:
0    False
1    False
2    False
3    False
4    False
dtype: bool


#Write a Pandas program to compare (equivalance,less than, greater than) the elements of the
two Pandas Series. Sample Series: [2, 4, 6, 8, 10], [1, 3, 5, 7, 9] and put them all series along with
comparisons results into a panda frame

In [55]:
import pandas as pd
ds1=pd.Series([2,4,6,8,10])
ds2=pd.Series([1,3,5,9,10])
Equals=ds1==ds2
Greaterthan=ds1>ds2
Lessthan=ds1<ds2
# converting pandas series into dictionary and then convert into dataframe
Data={'ds1':ds1,'ds2':ds2,'Equals':Equals,'Greaterthan':Greaterthan,'Lessthan':Lessthan}
df1=pd.DataFrame(Data)
df1

ds1  ds2  Equals  Greaterthan  Lessthan
0    2    1   False         True     False
1    4    3   False         True     False
2    6    5   False         True     False
3    8    9   False        False      True
4   10   10    True        False     False

In [57]:
print(df1.to_string(index=False))

 ds1  ds2  Equals  Greaterthan  Lessthan
   2    1   False         True     False
   4    3   False         True     False
   6    5   False         True     False
   8    9   False        False      True
  10   10    True        False     False


#Numpy provides a high-performance multidimensional array and basic tools to compute with
and manipulate the arrays. SciPy builds on this, and provides a large number of functions that
operate on numpy arrays and are useful for different types of scienti¦c and engineering
applications.

#Write a Pandas program to convert a NumPy array to a Pandas series.Sample NumPy array: d1 =
[10, 20, 30, 40, 50]

In [62]:
import numpy as np
import pandas as pd
np_array=np.array([1,2,3,4,5])
print("NumPy array:")
print(np_array)
new_series=pd.Series(np_array)
print("Converted Pandas series:")
print(new_series)

NumPy array:
[1 2 3 4 5]
Converted Pandas series:
0    1
1    2
2    3
3    4
4    5
dtype: int64


#Numpyt example program

#Write a NumPy program to generate five random numbers from the normal distribution.

In [82]:
import numpy as np
x = np.random.normal(size=5)
print(x)

[-0.62014976  0.57028021  0.11377089 -0.37117693  0.92736511]


#Write a NumPy program to generate six random integers between 10 and 30

In [83]:
import numpy as np
x = np.random.randint(low=10, high=30, size=6)
print(x)

[11 17 11 28 12 21]


#Write a NumPy program to create a 3x3x3 array with random values.

In [84]:
import numpy as np
x = np.random.random((3,3,3))
print(x)

[[[0.17189799 0.76698409 0.87511184]
  [0.9079104  0.68982632 0.72514626]
  [0.86121108 0.22195009 0.66844688]]

 [[0.84157764 0.97936791 0.27211523]
  [0.37378744 0.39603502 0.6058932 ]
  [0.13645735 0.82898317 0.21231185]]

 [[0.48212609 0.98752972 0.12882215]
  [0.4484443  0.36709854 0.62176328]
  [0.17337621 0.68115631 0.35780057]]]


#Write a NumPy program to create a 5x5 array with random values and find the minimum and maximum values.

In [85]:
import numpy as np
x = np.random.random((5,5))
print("Original Array:")
print(x) 
xmin, xmax = x.min(), x.max()
print("Minimum and Maximum Values:")
print(xmin, xmax)

Original Array:
[[0.46095277 0.86991266 0.12574645 0.43884371 0.65940231]
 [0.30703313 0.47564706 0.42521359 0.90986591 0.76519368]
 [0.81851983 0.7620701  0.37706404 0.71666248 0.99438355]
 [0.37333302 0.28791296 0.82136934 0.46039558 0.98859819]
 [0.61549205 0.92145825 0.67102768 0.98184541 0.32164813]]
Minimum and Maximum Values:
0.12574644670240465 0.9943835462812317


#Write a NumPy program to create a random 10x4 array and extract the first five rows of the  array and store them into a variable.

In [86]:
import numpy as np
x = np.random.rand(10, 4)
print("Original array: ")
print(x)
y= x[:5, :]
print("First 5 rows of the above array:")
y= x[:5, :]
print(y)
z= x[:, :4]
print("First 3 columns of the above array:")
print(z)

Original array: 
[[0.4085791  0.24755926 0.33291296 0.35769663]
 [0.26289049 0.43656884 0.85754165 0.3858698 ]
 [0.54661182 0.11017691 0.33505986 0.07705235]
 [0.4307952  0.9162908  0.8581512  0.63902519]
 [0.29823104 0.09838639 0.24298635 0.6357357 ]
 [0.37528838 0.61129895 0.03479099 0.21638859]
 [0.35094719 0.38505186 0.14188208 0.10770929]
 [0.09426367 0.11669445 0.56098853 0.04770277]
 [0.17940693 0.71650221 0.97225715 0.40309559]
 [0.66515063 0.25663492 0.46647486 0.7913825 ]]
First 5 rows of the above array:
[[0.4085791  0.24755926 0.33291296 0.35769663]
 [0.26289049 0.43656884 0.85754165 0.3858698 ]
 [0.54661182 0.11017691 0.33505986 0.07705235]
 [0.4307952  0.9162908  0.8581512  0.63902519]
 [0.29823104 0.09838639 0.24298635 0.6357357 ]]
First 3 columns of the above array:
[[0.4085791  0.24755926 0.33291296 0.35769663]
 [0.26289049 0.43656884 0.85754165 0.3858698 ]
 [0.54661182 0.11017691 0.33505986 0.07705235]
 [0.4307952  0.9162908  0.8581512  0.63902519]
 [0.29823104 0.0983

#Write a NumPy program to shuffle numbers and find permutation  between 0 and 10 (inclusive).

In [87]:
import numpy as np
x = np.arange(10)
np.random.shuffle(x)
print(x)
print("Same result using permutation():")
print(np.random.permutation(10))

[8 2 1 9 4 6 0 3 5 7]
Same result using permutation():
[4 9 0 1 7 5 2 6 3 8]


#Write a NumPy program to create a random integer nos of size 10 and sort it.

In [95]:
import numpy as np
x=np.arange(10)
np.random.randint(x)
print (x)

ValueError: ignored

#Write a NumPy program to create a random integer nos of size 10 and sort it.

In [89]:
import numpy as np
x=np.arange(10)
np.random.shuffle(x)
print(x)
x.sort()
print(x)

[1 5 7 0 8 2 3 4 9 6]
[0 1 2 3 4 5 6 7 8 9]


In [64]:
import numpy as np
x1=np.random.randint(100,size=6)
# One-dimensional array
x2=np.random.randint(100,size=(3,4))
# Two-dimensional array
x3=np.random.randint(100,size=(3,4,5))
# Three-dimensional array
print(x1)
print(x2)
print(x3)

[23 59 81 33 92 11]
[[78 12 83 10]
 [88 11 21 34]
 [61 55 19 36]]
[[[29 11  3 76 37]
  [67 71  2 65 52]
  [46 30  6 93 40]
  [82 61 50 84 11]]

 [[16 13 87 23 82]
  [58 63 41 21 15]
  [19 24 87 26 11]
  [34 91 33  9 93]]

 [[59 43 68 38 57]
  [10 82 91 33 25]
  [75 88 65  7 26]
  [40 19 21 70 30]]]


#Write a Pandas program to change the data type of the given meric ['100', '200', 'python', '300.12','400a']

In [65]:
import pandas as pd
s1=pd.Series(['100','200','python','300.12','400a'])
print("Original Data Series:")
print(s1)
print("Change the said data type to numeric:")
s2=pd.to_numeric(s1,errors='coerce')
print(s2)

Original Data Series:
0       100
1       200
2    python
3    300.12
4      400a
dtype: object
Change the said data type to numeric:
0    100.00
1    200.00
2       NaN
3    300.12
4       NaN
dtype: float64


#program to sort a given Series.

In [66]:
import pandas as pd
s=pd.Series(['200','100','python','300.12','400'])
print("Original Data Series:")
print(s)
new_s=pd.Series(s).sort_values()
print("sorted series are")
print(new_s)

Original Data Series:
0       200
1       100
2    python
3    300.12
4       400
dtype: object
sorted series are
1       100
0       200
3    300.12
4       400
2    python
dtype: object


#Write a Pandas program to add some data to an existing Series.

In [68]:
import pandas as pd
s=pd.Series(['100','200','python','300.12','400'])
print("Original Data Series:")
print(s)
print("\nData Series after adding some data:")
new_s=s.append(pd.Series(['500','php']))
print(new_s)

Original Data Series:
0       100
1       200
2    python
3    300.12
4       400
dtype: object

Data Series after adding some data:
0       100
1       200
2    python
3    300.12
4       400
0       500
1       php
dtype: object


#Write a Pandas program to create a subset of a given series based on value and condition

In [69]:
import pandas as pd
s=pd.Series([0,1,2,3,4,5,6,7,8,9,10])
print("Original Data Series:")
print(s)
n=6
new_s=s[s>n]
print("The values greater than 6")
print(new_s)
new_s1=s[s%2!=0]
print("The odd values ")
print(new_s1)

Original Data Series:
0      0
1      1
2      2
3      3
4      4
5      5
6      6
7      7
8      8
9      9
10    10
dtype: int64
The values greater than 6
7      7
8      8
9      9
10    10
dtype: int64
The odd values 
1    1
3    3
5    5
7    7
9    9
dtype: int64


#Write a program to create the mean and standard deviation, maximum and minimum of the data of a given Series using pandas

In [70]:
import pandas as pd
s=pd.Series(data=[1,2,3,4,5,6,7,8,9,5,3])
print("Original Data Series:")
print(s)
print("Mean of the said Data Series:")
print(s.mean())
print("Standard deviation of the said Data Series:")
print(s.std())
print("Max")
print(s.max())
print("Min")
print(s.min())

Original Data Series:
0     1
1     2
2     3
3     4
4     5
5     6
6     7
7     8
8     9
9     5
10    3
dtype: int64
Mean of the said Data Series:
4.818181818181818
Standard deviation of the said Data Series:
2.522624895547565
Max
9
Min
1


#Write a program to get the elements of an array values into column-wise using pandas Sample data: {‘X’:[78,85,96,80,86], 'Y':[84,94,89,83,86],'Z':[86,97,96,72,83]}

In [71]:
import pandas as pd
df=pd.DataFrame({'X':[78,85,96,80,86],'Y':[84,94,89,83,86],'Z':[86,97,96,72,83]});
print(df)

    X   Y   Z
0  78  84  86
1  85  94  97
2  96  89  96
3  80  83  72
4  86  86  83


#The previous program's index has to be removed instead convert into the data frame of the subject marks of X,Y,Z

In [72]:
df=pd.DataFrame({'X':[78,85,96,80,86],'Y':[84,94,89,83,86],'Z':[86,97,96,72,83],'Subjects':['Kanada','English','Maths','Science','Social']});
print(df.set_index('Subjects'))

           X   Y   Z
Subjects            
Kanada    78  84  86
English   85  94  97
Maths     96  89  96
Science   80  83  72
Social    86  86  83


#Write a program to get the columns of the DataFrame phone_data.csv using pandas

#The following lines have to be added to include CSV ¦le into colab

##import io
##uploaded=files.upload()

##df2=pd.read_csv(io.BytesIO(uploaded['phone_data.csv']))

In [78]:
import pandas as pd
import numpy as np
import io
from google.colab import files
uploaded=files.upload()
df2=pd.read_csv(io.BytesIO(uploaded['phone_data.csv']))
print("Columns of the DataFrame:")
print(df2.columns)
df2
df2.shape

Saving phone_data.csv to phone_data.csv
Columns of the DataFrame:
Index(['index', 'date', 'duration', 'item', 'month', 'network',
       'network_type'],
      dtype='object')


(830, 7)

#sorting based on date

In [79]:
d_df=df2[['index','date','duration','item','month','network']]
result=d_df.sort_values('network')
print("DataFrame based on network.")
print(result)
result1=d_df.sort_values('date')
print("DataFrame based on date.")
print(result1)

DataFrame based on network.
     index            date  duration  item    month network
293    293  25/11/14 16:09       1.0   sms  2014-12  Meteor
430    430  22/12/14 11:22       1.0   sms  2015-01  Meteor
524    524  05/01/15 11:58      99.0  call  2015-01  Meteor
425    425  21/12/14 00:05      54.0  call  2015-01  Meteor
423    423  20/12/14 15:53     553.0  call  2015-01  Meteor
..     ...             ...       ...   ...      ...     ...
370    370  07/12/14 23:22       1.0   sms  2014-12   world
371    371  07/12/14 23:22       1.0   sms  2014-12   world
828    828  14/03/15 00:13       1.0   sms  2015-03   world
361    361  06/12/14 18:28       1.0   sms  2014-12   world
829    829  14/03/15 00:16       1.0   sms  2015-03   world

[830 rows x 6 columns]
DataFrame based on date.
     index            date  duration  item    month   network
504    504  01/01/15 06:58    34.429  data  2015-01      data
673    673  01/02/15 06:58    34.429  data  2015-02      data
674    674  01/02

#Write a Pandas program to display the ¦rst 10 rows of the DataFrame.

In [81]:
import pandas as pd
import numpy as np
import io
from google.colab import files
uploaded=files.upload()
df2=pd.read_csv(io.BytesIO(uploaded['iris.csv']))
print("Columns of the DataFrame:")
print(df2.columns)
df2
df2.shape
#Display the first 10 rows
result=df2.head(10)
print("First 10 rows of the DataFrame:")
print(result)

Saving iris.csv to iris (1).csv
Columns of the DataFrame:
Index(['5.1', '3.5', '1.4', '0.2', 'Iris-setosa'], dtype='object')
First 10 rows of the DataFrame:
   5.1  3.5  1.4  0.2  Iris-setosa
0  4.9  3.0  1.4  0.2  Iris-setosa
1  4.7  3.2  1.3  0.2  Iris-setosa
2  4.6  3.1  1.5  0.2  Iris-setosa
3  5.0  3.6  1.4  0.2  Iris-setosa
4  5.4  3.9  1.7  0.4  Iris-setosa
5  4.6  3.4  1.4  0.3  Iris-setosa
6  5.0  3.4  1.5  0.2  Iris-setosa
7  4.4  2.9  1.4  0.2  Iris-setosa
8  4.9  3.1  1.5  0.1  Iris-setosa
9  5.4  3.7  1.5  0.2  Iris-setosa


#Day 3 Session 2 Exercises

#Pandas  and Numpy Exercise

#Write a Pandas program to create and display a one-dimensional array using series  containing  event numbers upto 10000
#tip : use List Comprehension
#ds = pd.Series([0,2, 4, 6, 8..... 10000])

In [97]:
import pandas as pd
ds=pd.Series([x for x in range(1000) if x%2==0])
ds

0        0
1        2
2        4
3        6
4        8
      ... 
495    990
496    992
497    994
498    996
499    998
Length: 500, dtype: int64

#Write a Pandas program to convert a Panda module Series of the numbers which are between 1000 and 2000 (both inclusive) and divisable by 5 to Python list and  after convertion print its type 

In [99]:
import pandas as pd
ds=pd.Series([x for x in range(1000,2001) if x%5==0])
ds



0      1000
1      1005
2      1010
3      1015
4      1020
       ... 
196    1980
197    1985
198    1990
199    1995
200    2000
Length: 201, dtype: int64

#Write a Pandas program to add, subtract, multiple and divide two Pandas Series and print their results using the Sample Series: [2, 4, 6, 8, ...100], [1, 3, 5, 7, 9...99]

In [100]:
import pandas as pd
ds1 = pd.Series([2, 4, 6, 8, 10])
ds2 = pd.Series([1, 3, 5, 7, 9])
ds = ds1 + ds2
print("Add two Series:")
print(ds)
print("Subtract two Series:")
ds = ds1 - ds2
print(ds)
print("Multiply two Series:")
ds = ds1 * ds2
print(ds)
print("Divide Series1 by Series2:")
ds = ds1 / ds2
print(ds)

Add two Series:
0     3
1     7
2    11
3    15
4    19
dtype: int64
Subtract two Series:
0    1
1    1
2    1
3    1
4    1
dtype: int64
Multiply two Series:
0     2
1    12
2    30
3    56
4    90
dtype: int64
Divide Series1 by Series2:
0    2.000000
1    1.333333
2    1.200000
3    1.142857
4    1.111111
dtype: float64


#Write a Pandas program to compare (Equivalence, greater than, less than, not equal to )the elements of the two Pandas Series.
#Sample Series: [All positive numbers divisable by 7 upto 1000], [All positive numbers divisable by 11 upto 1000]

In [110]:
import pandas as pd
ds1=pd.Series([2, 4, 6, 8, 10])
ds2=pd.Series([1, 3, 5, 7, 10])
print("Series1:")
ds1
print("Series2:")
ds2
print("Compare the elements of the said Series:")
print("Equals:")
print(ds1 == ds2)
print("Greater than:")
print(ds1 > ds2)
print("Less than:")
print(ds1 < ds2)

Series1:
Series2:
Compare the elements of the said Series:
Equals:
0    False
1    False
2    False
3    False
4     True
dtype: bool
Greater than:
0     True
1     True
2     True
3     True
4    False
dtype: bool
Less than:
0    False
1    False
2    False
3    False
4    False
dtype: bool


#Write a Pandas program to convert a NumPy array to a Pandas series. 
#Sample NumPy array: d1 = [10, 20, 30, 40, 50... 1000]

In [111]:
import numpy as np
import pandas as pd
np_array = np.array([10, 20, 30, 40, 50])
print("NumPy array:")
print(np_array)
new_series = pd.Series(np_array)
print("Converted Pandas series:")
print(new_series)

NumPy array:
[10 20 30 40 50]
Converted Pandas series:
0    10
1    20
2    30
3    40
4    50
dtype: int64


#Write a Pandas program to convert a given Series to an array.Sample series is ['100', '200', ‘300’,’400’,’500’,'python', '300.12', '400',’is’,’great’,’language’]

In [112]:
import pandas as pd
import numpy as np
s1 = pd.Series(['100', '200', '300','400','500','python', '300.12', '400','is','great','language'])
print("Original Data Series:")
print(s1)
print("Series to an array")
a = np.array(s1.values.tolist())
print (a)

Original Data Series:
0          100
1          200
2          300
3          400
4          500
5       python
6       300.12
7          400
8           is
9        great
10    language
dtype: object
Series to an array
['100' '200' '300' '400' '500' 'python' '300.12' '400' 'is' 'great'
 'language']


#Write a Pandas program to create a subsets of a given series based on value and condition.Sample NumPy array: d1 = [10, 20, 30, 40, 50... 1000] value and condtion : Subset 1 :numbers divisable by 7 Subset 2 : numbers divisable by 5

In [113]:
import pandas as pd
s = pd.Series([0, 1,2,3,4,5,6,7,8,9,10])
print("Original Data Series:")
print(s)
print("\nSubset of the above Data Series:")
n = 6
new_s = s[s < n]
print(new_s)

Original Data Series:
0      0
1      1
2      2
3      3
4      4
5      5
6      6
7      7
8      8
9      9
10    10
dtype: int64

Subset of the above Data Series:
0    0
1    1
2    2
3    3
4    4
5    5
dtype: int64


#Write a Pandas program to create the mean and standard deviation, maximum and minimum of the data of a given Series of the prime numbers upto 1000

In [114]:
import pandas as pd
s = pd.Series(data = [x for x in range(1000) if x%2==0])
print("Original Data Series:")
print(s)
print("Mean of the said Data Series:")
print(s.mean())
print("Standard deviation of the said Data Series:")
print(s.std())

Original Data Series:
0        0
1        2
2        4
3        6
4        8
      ... 
495    990
496    992
497    994
498    996
499    998
Length: 500, dtype: int64
Mean of the said Data Series:
499.0
Standard deviation of the said Data Series:
288.9636655359978


#Write a Pandas program to get the elements of an array values into column-wise.Sample data: {‘X’:[All odd numbers but not divisable by 7 upto 1000], 'Y':[ All even numbers but not divisable by 5 upto 1000 ],'Z':[ All odd numbers but not divisable by 3 upto 1000]}

In [115]:
import pandas as pd
df = pd.DataFrame({'X':[78,85,96,80,86], 'Y':[84,94,89,83,86],'Z':[86,97,96,72,83]});
print(df)

    X   Y   Z
0  78  84  86
1  85  94  97
2  96  89  96
3  80  83  72
4  86  86  83


#Write a Pandas program to display the first 10 rows of the DataFrame for any particular three fields.

In [116]:
import pandas as pd
import numpy as np

exam_data  = {'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'],
        'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
        'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
        'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']}
labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']

df = pd.DataFrame(exam_data , index=labels)
print("First three rows of the data frame:")
print(df.iloc[:3])

First three rows of the data frame:
        name  score  attempts qualify
a  Anastasia   12.5         1     yes
b       Dima    9.0         3      no
c  Katherine   16.5         2     yes


#Write a Pandas program to get the details of the seventh movie of the DataFrame for any particular three fields 
#(movie_metadata.csv file).

In [126]:
!pip install -U -q PyDrive
from pydrive.auth import GoogleAuth
from pydrive.drive import GoogleDrive
from google.colab import auth
from oauth2client.client import GoogleCredentials

In [133]:
auth.authenticate_user()
gauth = GoogleAuth()
gauth.credentials = GoogleCredentials.get_application_default()
drive = GoogleDrive(gauth)

In [139]:
import pandas as pd
xyz = pd.read_csv('movies_metadata.csv') 
print(xyz.head(1))

   adult  ... vote_count
0  False  ...     5415.0

[1 rows x 24 columns]


/usr/local/lib/python3.6/dist-packages/IPython/core/interactiveshell.py:2718: DtypeWarning: Columns (10) have mixed types.Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)


In [140]:
import pandas as pd
df = pd.read_csv('movies_metadata.csv')
seventh_movie = df.iloc[3]
print("Details of the seventh movie:")
print(seventh_movie)

Details of the seventh movie:
adult                                                                False
belongs_to_collection                                                  NaN
budget                                                            16000000
genres                   [{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...
homepage                                                               NaN
id                                                                   31357
imdb_id                                                          tt0114885
original_language                                                       en
original_title                                           Waiting to Exhale
overview                 Cheated on, mistreated and stepped on, the wom...
popularity                                                         3.85949
poster_path                               /16XOMpEaLWkrcPqSQqhTmeJuqQl.jpg
production_companies     [{'name': 'Twentieth Century Fox Film Corpora

/usr/local/lib/python3.6/dist-packages/IPython/core/interactiveshell.py:2718: DtypeWarning: Columns (10) have mixed types.Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)


#Write a Pandas program to sort the DataFrame based on title_year from dataset of movie_metadata.csv for any particular three fields 

In [142]:
import pandas as pd
df = pd.read_csv('movies_metadata.csv')
result = df[['title', 'genres']]
print("Details of title and genres:")
print(result)

Details of title and genres:
                             title                                             genres
0                        Toy Story  [{'id': 16, 'name': 'Animation'}, {'id': 35, '...
1                          Jumanji  [{'id': 12, 'name': 'Adventure'}, {'id': 14, '...
2                 Grumpier Old Men  [{'id': 10749, 'name': 'Romance'}, {'id': 35, ...
3                Waiting to Exhale  [{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...
4      Father of the Bride Part II                     [{'id': 35, 'name': 'Comedy'}]
...                            ...                                                ...
45461                       Subdue  [{'id': 18, 'name': 'Drama'}, {'id': 10751, 'n...
45462          Century of Birthing                      [{'id': 18, 'name': 'Drama'}]
45463                     Betrayal  [{'id': 28, 'name': 'Action'}, {'id': 18, 'nam...
45464             Satan Triumphant                                                 []
45465                    

/usr/local/lib/python3.6/dist-packages/IPython/core/interactiveshell.py:2718: DtypeWarning: Columns (10) have mixed types.Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)


#Write a NumPy program to create a random 4x4 array and extract the 2nd and 3rd rows of the array and store them into a variable

In [143]:
import numpy as np
x = np.random.random((4,4))
print("Original Array:")
print(x)

Original Array:
[[0.06983272 0.28980912 0.63569294 0.24733063]
 [0.91820096 0.03578891 0.24069499 0.33000368]
 [0.97149688 0.86510127 0.56765916 0.82670019]
 [0.8101744  0.56709461 0.2570201  0.31083467]]


#Write a NumPy program to create a 10x10 array with random values and find the minimum and maximum values.

In [144]:
import numpy as np
x = np.random.random((10,10))
print("Original Array:")
print(x) 
xmin, xmax = x.min(), x.max()
print("Minimum and Maximum Values:")
print(xmin, xmax)

Original Array:
[[0.96056966 0.76698316 0.05196466 0.89290757 0.87124973 0.24826924
  0.63177262 0.46374921 0.76707225 0.44338203]
 [0.24842129 0.54613029 0.93545891 0.74203045 0.33953046 0.67706178
  0.43993317 0.00850165 0.56840008 0.888496  ]
 [0.66957248 0.58800942 0.30363214 0.54753603 0.31856679 0.42248326
  0.3886181  0.01056804 0.89582183 0.88735061]
 [0.74171713 0.37091243 0.0968546  0.22044527 0.18284768 0.51553744
  0.65907219 0.70306703 0.46138601 0.94755613]
 [0.59397464 0.22474364 0.10718924 0.89757288 0.05766916 0.91735753
  0.94904497 0.6604946  0.15283303 0.05105154]
 [0.93733065 0.40741104 0.39790091 0.43368259 0.90217219 0.95073529
  0.00939634 0.86092763 0.48062146 0.78652141]
 [0.61709028 0.00417909 0.44116302 0.86884205 0.27941244 0.77653963
  0.32472133 0.60810919 0.65208902 0.72908248]
 [0.73620645 0.11075692 0.272515   0.78984961 0.19971725 0.69193465
  0.63619984 0.86796411 0.05274678 0.07753537]
 [0.75106193 0.85114017 0.89597395 0.05065669 0.12387795 0.18622

#Write a NumPy program to generate 8 random integers between 100 and 300

In [145]:
import numpy as np
x = np.random.randint(low=100, high=300, size=8)
print(x)

[291 257 177 242 102 156 230 120]


#Write a NumPy program to create a random integer nos of size 20 and sort it.

In [146]:
import numpy as np
x = np.random.random(20)
print("Original array:")
print(x)
x.sort()
print("Sorted array:")
print(x)

Original array:
[0.13379268 0.0112629  0.11136029 0.39246852 0.95033293 0.22196726
 0.07042969 0.4888782  0.8522031  0.0139328  0.01527421 0.22504374
 0.19814965 0.39407236 0.32337489 0.78643552 0.46154745 0.41647646
 0.91981875 0.79736514]
Sorted array:
[0.0112629  0.0139328  0.01527421 0.07042969 0.11136029 0.13379268
 0.19814965 0.22196726 0.22504374 0.32337489 0.39246852 0.39407236
 0.41647646 0.46154745 0.4888782  0.78643552 0.79736514 0.8522031
 0.91981875 0.95033293]
